name: Build App

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crear build
        run: |
          mkdir dist
          echo "build ok" > dist/app.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/