name: Build App

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Compilar aplicación
        run: |
          mkdir dist
          echo "Aplicación compilada correctamente" > dist/app.txt

      - name: Mostrar environment
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev'
        run: echo "Environment: dev"

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/